language: node_js

# https://github.com/nodejs/Release
node_js:
- 10 # EOL: April 2021
- 8 # EOL: December 2019
- 6 # EOL: April 2019

os:
  - linux

matrix:
  fast_finish: true
  include:
    - node_js: 8
      os: windows
      env: YARN_GPG=no # starts gpg-agent that never exits
    - node_js: 8
      os: osx
    - name: "Production build"
      node_js: 8 # Version used to deploy to npm registry
      os: linux
      env: BUILD_ENV=production

cache: yarn

before_script:
  - NODE_ENV=$BUILD_ENV yarn build

install:
  - yarn --frozen-lockfile --non-interactive --network-timeout 300000

notifications:
  email:
    on_success: never
    on_failure: always

# Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
before_deploy: |
  function npm_dist_tag() {
    if [[ "$TRAVIS_TAG" = *"-"* ]]; then
      echo "next"
    else
      echo "latest"
    fi
  }

deploy:
  skip_cleanup: true # prevent git stash --all which nukes node_modules folder
  provider: npm
  tag: $(npm_dist_tag)
  email:
    secure: Eb/dO3VEnuG5CFSJbiTBDZ4X29o1bTITqfzc4SZJqkSKHLZ5/l0VHyd1In7T2U9yBtysnmm+dsOWYFwnH5NMt5kvGkkX754HBDz0QXO//IqADA/1cH1MMXuzJjRvHNrtbq3c6Iv0vO827kXfvqwkfGTmXfreT5w+xF7Y+0SjF8pfu2d/Z5omrmoy9J9SF/kfmahKYZwakc3h8p29JPmnFMUAR0JiZS/2gLSHQnGA3mCcnlO+U3bQuTVW3Z9RhiG51f/EMFfNZ8pBttM6CgE2Zth3AT50jbKjRgYdYN2ee/Z3qUJIoA6dfPALC7B+Z2UekqTiKx4SCk+9vZJJXqT8J+Fe67Dki/FgNWnEZaTn8eFs+Gfh2nnokNZUMd/2mMT0y0KbRaOYQarn6lFw+/Cn9hD6e8uRCqY0+YspMvGtV3LuHFy+br6YphlG6YKxJzExtGDvrwlDD70xJtqcgnlET3XOdzvfCpRSskh7FmVJMoL39f/j9r4FzWVDmfnRnDT6Cac2dSdbQM0Ldw3+65l/57K/Km7NeHbLA3LsnjSJqXuysYwosd6iUOQen59Dy+TvwKafEfAGXWcZNguFURIMf2LRZ4rwTZl6pp30nj23U6rmkWm3JTRZC95i/O4yP2rVoljNUEuMlHVts63r3lwXtuGQVo3+lQCYErK4Ceo7cQc=
  api_key:
    secure: jC3E9s+9XJOX/dgcOzzsB4rDvNlhSb6AqBstga2gWmNu2MLZ7+ZzTghN9XnvdNi8EIzvM0sJlWHvGmVBT2RHmoLE4y6nidssN/DzplHyhdQMewGZfmzHcNbBjey6ooGodBVBCdHS4AhCw8r8FCItgcFuJ9trNYRC3va/gVlzin4zfUqOOsin+SHGFtD3nRPu50Kffw7wZYRyHjTLRmewF5KfIKNXOzugUanIwWLYfd2tOSBj2eu+zrQf5u+Oie8CJXYNDeE/aHC0S8BH51tgCzlenetBKc9XE06brVDYaFiFZuE7uBfQFWQNKkXF9eVL/JeEHWilLpU6O0Lj8mgkCytcP4m3oZEG6kL/4UOrtGoEj/I0PRFhIMN6L6HnX4fOfgubp9mIyEmkXSc4BI10Nxb8rKz3GrmwM1SOSjeKjChDj3sBVzuSllMLMlwnNSziEPqo/iaslqbmk/l7w7fnSJqGvCuhoweL8uIgpdcM3zNvfZx+Cv3CpAoDJJE/NVCY/hqVgkhyjzKMCkenz/mZy8eq0o7AMVBp0Xo1xDhaNleOOSxP/uzMo6C6d2C7GQhWlAfSjDEyPO0nbBhYu9ZxWBUh9Gf7PObaUtPIYPhmaf5YXB9DDn22xm3vJc9dg8KkxF2zPI30UR/hqN/umffQ61VQIc8evh+38edaEtUgF2c=
  on:
    node: 8
    condition: "$BUILD_ENV = production"
    tags: true
    repo: thelounge/thelounge

# If the current release is a stable release, remove potential pre-release tag
after_deploy: |
  if [ "$(npm_dist_tag)" == "latest" ]; then
    yarn tag remove thelounge next || true
  fi
