---
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Do not build on tags (GitHub only)
skip_tags: true

# Do not build feature branch with open pull requests
skip_branch_with_pr: true

environment:
  nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry npm install
  - npm run build
  - npm install mocha-appveyor-reporter
  - echo --reporter mocha-appveyor-reporter >> test/mocha.opts

test_script:
  - node --version
  - npm --version
  - npm test

# cache npm modules
cache:
  - '%AppData%\npm-cache -> package.json'

# Don't actually build
build: off
