---
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Do not build on tags (GitHub only)
skip_tags: true

environment:
  nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run test:mocha
  - npm run lint:js
  - npm run lint:css

# Don't actually build
build: off
