contact_links:
  - name: Docker container issues
    url: https://github.com/thelounge/thelounge-docker/issues
    about: Report issues related to the Docker container here

  - name: Debian package issues
    url: https://github.com/thelounge/thelounge-deb/issues
    about: Report issues related to the Debian package here

  - name: Arch Linux package issues
    url: https://github.com/thelounge/thelounge-archlinux/issues
    about: Report issues related to the Arch Linux package here

  - name: General support
    url: https://demo.thelounge.chat/?join=%23thelounge
    about: "Join #thelounge on Libera.Chat to ask a question before creating an issue"
